"""
配置文件：存放venue配置等常量
"""
import os

# 从环境变量读取配置
MAX_CROSSREF_WORKERS = int(os.getenv("MAX_CROSSREF_WORKERS", "6"))
MAX_FILTERING_WORKERS = int(os.getenv("MAX_FILTERING_WORKERS", "5"))

# --- Business Journals ---
JOURNAL_VENUES = {
    "ISR": "Information Systems Research",
    "MISQ": "MIS Quarterly",
    "MS": "Management Science",
    "MKS": "Marketing Science",
    "JOC": "INFORMS Journal on Computing",
    "TAR": "The Accounting Review",
    "JAE": "Journal of Accounting and Economics",
    "JAR": "Journal of Accounting Research",
    "JF": "Journal of Finance",
    "JFE": "Journal of Financial Economics",
    "RFS": "Review of Financial Studies",
    "JM": "Journal of Marketing",
    "JMR": "Journal of Marketing Research",
    "JCR": "Journal of Consumer Research",
    "OR": "Operations Research",
    "JOM": "Journal of Operations Management",
    "MSOM": "Manufacturing & Service Operations Management",
    "POM": "Production and Operations Management",
    "AMJ": "Academy of Management Journal",
    "AMR": "Academy of Management Review",
    "ASQ": "Administrative Science Quarterly",
    "OrgSci": "Organization Science",
    "JIBS": "Journal of International Business Studies",
    "SMJ": "Strategic Management Journal",
    "AER": "American Economic Review",
    "N/S": "Nature",
}

# --- CS Conferences ---
CONFERENCE_VENUES = {
    "NeurIPS": "Advances in Neural Information Processing Systems",
    "ICML": "International Conference on Machine Learning",
    "ICLR": "International Conference on Learning Representations",
    "AAAI": "AAAI Conference on Artificial Intelligence",
    "IJCAI": "International Joint Conference on Artificial Intelligence",
    "UAI": "Conference on Uncertainty in Artificial Intelligence",
    "ACL": "Association for Computational Linguistics",
    "EMNLP": "Empirical Methods in Natural Language Processing",
    "NAACL": "North American Chapter of the Association for Computational Linguistics",
    "COLING": "International Conference on Computational Linguistics",
    "CVPR": "Computer Vision and Pattern Recognition",
    "ICCV": "International Conference on Computer Vision",
    "ECCV": "European Conference on Computer Vision",
    "KDD": "Knowledge Discovery and Data Mining",
    "WWW": "The Web Conference",
    "SIGIR": "Special Interest Group on Information Retrieval",
    "SIGMOD": "Special Interest Group on Management of Data",
    "VLDB": "Very Large Data Bases",
    "SOSP": "Symposium on Operating Systems Principles",
    "OSDI": "Operating Systems Design and Implementation",
    "NSDI": "Networked Systems Design and Implementation",
    "ASPLOS": "Architectural Support for Programming Languages and Operating Systems",
    "SIGCOMM": "Special Interest Group on Data Communication",
    "IEEE S&P": "Symposium on Security and Privacy",
    "USENIX Security": "USENIX Security Symposium",
    "ACM CCS": "Conference on Computer and Communications Security",
    "ICSE": "International Conference on Software Engineering",
    "CHI": "Conference on Human Factors in Computing Systems",
    "POPL": "Principles of Programming Languages",
    "PLDI": "Programming Language Design and Implementation",
    "STOC": "Symposium on Theory of Computing",
    "FOCS": "Foundations of Computer Science",
    "SIGGRAPH": "Special Interest Group on Computer Graphics",
    "ICRA": "International Conference on Robotics and Automation",
    "AOM": "Academy of Management Annual Meeting",
}

CONFERENCE_NAME_FILTERS = {
    "NeurIPS": ["neural information processing systems", "neurips", "advances in neural information processing systems"],
    "ICML": ["international conference on machine learning", "icml"],
    "ICLR": ["international conference on learning representations", "iclr", "learning representations"],
    "AAAI": ["aaai conference on artificial intelligence", "aaai", "association for the advancement of artificial intelligence"],
    "IJCAI": ["international joint conference on artificial intelligence", "ijcai"],
    "UAI": ["conference on uncertainty in artificial intelligence", "uai"],
    "ACL": ["annual meeting of the association for computational linguistics", "proceedings of the association for computational linguistics", "findings of the association for computational linguistics", "acl 20", "association for computational linguistics"],
    "EMNLP": ["empirical methods in natural language processing", "emnlp"],
    "NAACL": ["north american chapter of the association for computational linguistics", "naacl"],
    "COLING": ["international conference on computational linguistics", "coling"],
    "CVPR": ["computer vision and pattern recognition", "cvpr"],
    "ICCV": ["international conference on computer vision", "iccv"],
    "ECCV": ["european conference on computer vision", "eccv"],
    "KDD": ["knowledge discovery and data mining", "kdd"],
    "WWW": ["world wide web", "www", "the web conference"],
    "SIGIR": ["special interest group on information retrieval", "sigir", "information retrieval"],
    "SIGMOD": ["special interest group on management of data", "sigmod", "management of data"],
    "VLDB": ["very large data bases", "vldb"],
    "SOSP": ["symposium on operating systems principles", "sosp"],
    "OSDI": ["operating systems design and implementation", "osdi"],
    "NSDI": ["networked systems design and implementation", "nsdi"],
    "ASPLOS": ["architectural support for programming languages", "asplos"],
    "SIGCOMM": ["special interest group on data communication", "sigcomm", "data communication"],
    "IEEE S&P": ["symposium on security and privacy", "security and privacy", "ieee s&p", "oakland"],
    "USENIX Security": ["usenix security", "usenix security symposium"],
    "ACM CCS": ["conference on computer and communications security", "ccs", "computer and communications security"],
    "ICSE": ["international conference on software engineering", "icse"],
    "CHI": ["conference on human factors", "chi", "human factors in computing systems"],
    "POPL": ["principles of programming languages", "popl"],
    "PLDI": ["programming language design and implementation", "pldi"],
    "STOC": ["symposium on theory of computing", "stoc"],
    "FOCS": ["foundations of computer science", "focs"],
    "SIGGRAPH": ["special interest group on computer graphics", "siggraph", "computer graphics"],
    "ICRA": ["international conference on robotics and automation", "icra"],
    "AOM": ["academy of management", "aom", "annual meeting of the academy"],
}
